"""
core/rbac/levels.py
===================
The two access levels and the three record visibilities.

From the paper:
  Global Access Level (Manager) — robots in supervisory roles get cross-client
    visibility, querying the global RAG layer and key-point memory to maintain a
    unified view of the user's history across the team.
  Local Access Level (Worker) — restricted to local isolation: queries are
    governed by the robot's own interaction history, and data generated by other
    platforms cannot be retrieved.

Both parsers fail closed. An unrecognised value raises rather than defaulting,
so a typo in a scenario profile or a corrupted DB row surfaces at boot or at the
policy boundary instead of silently granting access.
"""

from __future__ import annotations
from enum import Enum


class AccessLevel(str, Enum):
    """What a robot is allowed to reach. Declared per-deployment, stored on the DB."""

    GLOBAL = "global"   # Manager
    LOCAL = "local"     # Worker


class Visibility(str, Enum):
    """How widely a single memory record may be shared."""

    GLOBAL = "global"           # readable by Manager robots in the same scenario
    LOCAL = "local"             # readable by its source robot only
    RESTRICTED = "restricted"   # source robot plus an explicit delegation grant only


class InvalidAccessLevel(ValueError):
    """Raised when an access level cannot be parsed. Never resolves to a default."""


def parse_access_level(value: object) -> AccessLevel:
    """
    Parse an access level from a profile or DB row.

    Raises InvalidAccessLevel on anything unrecognised — including None and the
    empty string. Callers that want a deny decision rather than an exception
    should use policy.can_read, which catches this.
    """
    if isinstance(value, AccessLevel):
        return value
    if isinstance(value, str):
        try:
            return AccessLevel(value.strip().lower())
        except ValueError:
            pass
    raise InvalidAccessLevel(
        f"Unknown access level {value!r}. "
        f"Valid values: {', '.join(l.value for l in AccessLevel)}."
    )


def parse_visibility(value: object) -> Visibility:
    """
    Parse a record visibility. Raises ValueError on anything unrecognised,
    including None — a record with no visibility is not readable by anyone.
    """
    if isinstance(value, Visibility):
        return value
    if isinstance(value, str):
        try:
            return Visibility(value.strip().lower())
        except ValueError:
            pass
    raise ValueError(
        f"Unknown visibility {value!r}. "
        f"Valid values: {', '.join(v.value for v in Visibility)}."
    )
