"""
core/rbac/policy.py
===================
Pure access-control decisions. No I/O, no globals, no imports from the
application layer — every input arrives as an argument, so the whole matrix is
unit-testable without a database, a FAISS index or a running server.

Default deny. An unrecognised access level, a missing or unparseable
visibility, absent provenance, or an expired grant all resolve to deny, each
with its own reason so the audit log can count denials by cause.
"""

from __future__ import annotations
from datetime import datetime
from typing import Optional, Sequence

from core.rbac.grants import DelegationGrant
from core.rbac.levels import (
    AccessLevel,
    InvalidAccessLevel,
    Visibility,
    parse_access_level,
    parse_visibility,
)
from core.rbac.models import Decision, MemoryRecord, RobotIdentity


class Reason:
    """
    Stable decision reasons. These are persisted in rbac_audit_log and asserted
    on in tests, so treat them as a wire format: add freely, rename never.
    """

    # allow
    OWN_RECORD = "own_record"
    GLOBAL_ACCESS = "global_access"
    DELEGATION_GRANT = "delegation_grant"

    # deny
    INVALID_VISIBILITY = "invalid_visibility"
    UNKNOWN_ACCESS_LEVEL = "unknown_access_level"
    UNKNOWN_REQUESTER = "unknown_requester"
    MISSING_PROVENANCE = "missing_provenance"
    GRANT_EXPIRED = "grant_expired"
    SCENARIO_MISMATCH = "scenario_mismatch"
    RESTRICTED_RECORD = "restricted_record"
    LOCAL_ISOLATION = "local_isolation"
    RECORD_IS_LOCAL = "record_is_local"
    DEFAULT_DENY = "default_deny"


def can_read(
    requester: RobotIdentity,
    record: MemoryRecord,
    grants: Sequence[DelegationGrant],
    now: datetime,
) -> Decision:
    """
    Decide whether `requester` may read `record` at time `now`.

    Evaluation order (first match wins):

      1. record visibility must parse                  -> invalid_visibility
      2. requester access level must parse             -> unknown_access_level
      3. requester must be identifiable                -> unknown_requester
      4. the requester's own record                    -> ALLOW own_record
      5. an active grant naming this record            -> ALLOW delegation_grant
      6. a grant naming it, but expired                -> grant_expired
      7. record has no provenance                      -> missing_provenance
      8. Manager + global record + same scenario       -> ALLOW global_access
      9. everything else                               -> a specific deny

    Ownership is checked before scenario scoping deliberately: a robot can always
    read what it generated itself, and scenario scoping exists to bound
    *cross-robot* visibility. This is also what keeps legacy rows (scenario_id
    NULL, backfilled by 002_rbac.sql) readable by the robot that created them,
    so applying the migration changes no existing scenario's behaviour.
    """
    # ── 1. Visibility must be present and valid ───────────────────────────────
    try:
        visibility = parse_visibility(record.visibility)
    except ValueError:
        return Decision(False, Reason.INVALID_VISIBILITY)

    # ── 2. Access level must be present and valid ─────────────────────────────
    try:
        level = parse_access_level(requester.access_level)
    except InvalidAccessLevel:
        return Decision(False, Reason.UNKNOWN_ACCESS_LEVEL)

    # ── 3. The requester must be identifiable ─────────────────────────────────
    if not requester.robot_id:
        return Decision(False, Reason.UNKNOWN_REQUESTER)

    # ── 4. Own record ─────────────────────────────────────────────────────────
    if record.source_robot_id and record.source_robot_id == requester.robot_id:
        return Decision(True, Reason.OWN_RECORD)

    # ── 5/6. Delegation grants ────────────────────────────────────────────────
    # Grants only ever widen access, so they are consulted after ownership and
    # before the standing visibility rules.
    saw_expired_grant = False
    for grant in grants or ():
        if grant.granted_to != requester.robot_id:
            continue
        if not grant.covers(record.record_id):
            continue
        if grant.is_active(now):
            return Decision(True, Reason.DELEGATION_GRANT, matched_grant_id=grant.grant_id)
        saw_expired_grant = True

    if saw_expired_grant:
        return Decision(False, Reason.GRANT_EXPIRED)

    # ── 7. Provenance ─────────────────────────────────────────────────────────
    # An unattributed record cannot be reasoned about beyond an explicit grant.
    if not record.source_robot_id:
        return Decision(False, Reason.MISSING_PROVENANCE)

    # ── 8/9. Standing visibility rules ────────────────────────────────────────
    if level is AccessLevel.LOCAL:
        # Worker: local isolation. Data generated by other platforms is not
        # retrievable, whatever its visibility.
        return Decision(False, Reason.LOCAL_ISOLATION)

    if level is AccessLevel.GLOBAL:
        # Manager: cross-client visibility over global records, within scenario.
        if visibility is Visibility.RESTRICTED:
            return Decision(False, Reason.RESTRICTED_RECORD)
        if visibility is Visibility.LOCAL:
            return Decision(False, Reason.RECORD_IS_LOCAL)
        if not _same_scenario(requester, record):
            return Decision(False, Reason.SCENARIO_MISMATCH)
        return Decision(True, Reason.GLOBAL_ACCESS)

    return Decision(False, Reason.DEFAULT_DENY)


def _same_scenario(requester: RobotIdentity, record: MemoryRecord) -> bool:
    """
    Scenario scoping for cross-robot reads.

    Both sides must be set and equal. An unscoped record (scenario_id NULL, as
    left by the 002 backfill) never satisfies cross-robot visibility — it is
    reachable only by its source robot or through an explicit grant.
    """
    if not requester.scenario_id or not record.scenario_id:
        return False
    return requester.scenario_id == record.scenario_id


def default_visibility_for(level: object) -> Visibility:
    """
    The visibility a robot at `level` should stamp on records it writes, when the
    scenario profile does not override it.

    Always LOCAL, including for Managers. Widening is an explicit deployment
    decision (`default_visibility: global` in the scenario profile), never an
    implicit consequence of a robot's rank.
    """
    return Visibility.LOCAL
