"""
tests/test_rbac_policy.py
=========================
The full policy matrix: Manager/Worker x own/other/global records x
valid/expired/absent grant, plus every default-deny branch.

policy.can_read is pure, so none of this needs a database, an index or a server.
Assertions are on Decision.reason as well as the boolean — the audit log counts
denials by cause, so a right answer for the wrong reason is still a bug.
"""

from __future__ import annotations
from datetime import timedelta

import pytest

from core.rbac import AccessLevel, MemoryRecord, Reason, RobotIdentity, Visibility, can_read
from tests.conftest import MANAGER_ID, OTHER_WORKER_ID, SCENARIO, WORKER_ID, make_record


# ── Manager (GLOBAL) ──────────────────────────────────────────────────────────

class TestManagerAccess:

    def test_reads_own_record(self, manager, now):
        r = make_record(source=MANAGER_ID, visibility=Visibility.LOCAL)
        d = can_read(manager, r, (), now)
        assert d.allowed and d.reason == Reason.OWN_RECORD

    def test_reads_another_robots_global_record(self, manager, now):
        """Cross-client visibility — the unified view of the user's history."""
        r = make_record(source=WORKER_ID, visibility=Visibility.GLOBAL)
        d = can_read(manager, r, (), now)
        assert d.allowed and d.reason == Reason.GLOBAL_ACCESS

    def test_denied_another_robots_local_record(self, manager, now):
        r = make_record(source=WORKER_ID, visibility=Visibility.LOCAL)
        d = can_read(manager, r, (), now)
        assert not d.allowed and d.reason == Reason.RECORD_IS_LOCAL

    def test_denied_restricted_record(self, manager, now):
        r = make_record(source=WORKER_ID, visibility=Visibility.RESTRICTED)
        d = can_read(manager, r, (), now)
        assert not d.allowed and d.reason == Reason.RESTRICTED_RECORD

    def test_denied_across_scenarios(self, manager, now):
        """'Not across scenarios' — a Manager's reach stops at its deployment."""
        r = make_record(source=WORKER_ID, visibility=Visibility.GLOBAL,
                        scenario="hospital_reception")
        d = can_read(manager, r, (), now)
        assert not d.allowed and d.reason == Reason.SCENARIO_MISMATCH

    def test_denied_unscoped_record_from_another_robot(self, manager, now):
        """A legacy row (scenario_id NULL) never satisfies cross-robot visibility."""
        r = make_record(source=WORKER_ID, visibility=Visibility.GLOBAL, scenario=None)
        d = can_read(manager, r, (), now)
        assert not d.allowed and d.reason == Reason.SCENARIO_MISMATCH


# ── Worker (LOCAL) ────────────────────────────────────────────────────────────

class TestWorkerIsolation:

    def test_reads_own_record(self, worker, now):
        r = make_record(source=WORKER_ID, visibility=Visibility.LOCAL)
        d = can_read(worker, r, (), now)
        assert d.allowed and d.reason == Reason.OWN_RECORD

    def test_reads_own_record_regardless_of_visibility(self, worker, now):
        for vis in (Visibility.LOCAL, Visibility.GLOBAL, Visibility.RESTRICTED):
            d = can_read(worker, make_record(source=WORKER_ID, visibility=vis), (), now)
            assert d.allowed and d.reason == Reason.OWN_RECORD

    def test_denied_managers_record(self, worker, now):
        """The Manager's key-points are not retrievable by a Worker directly."""
        r = make_record(source=MANAGER_ID, visibility=Visibility.GLOBAL)
        d = can_read(worker, r, (), now)
        assert not d.allowed and d.reason == Reason.LOCAL_ISOLATION

    def test_denied_peer_workers_record(self, worker, now):
        """Data generated by other platforms cannot be retrieved."""
        r = make_record(source=OTHER_WORKER_ID, visibility=Visibility.GLOBAL)
        d = can_read(worker, r, (), now)
        assert not d.allowed and d.reason == Reason.LOCAL_ISOLATION

    def test_own_record_readable_even_in_another_scenario(self, worker, now):
        """
        Ownership is checked before scenario scoping, which is what keeps rows
        backfilled by 002_rbac.sql readable by the robot that created them.
        """
        r = make_record(source=WORKER_ID, visibility=Visibility.LOCAL, scenario=None)
        d = can_read(worker, r, (), now)
        assert d.allowed and d.reason == Reason.OWN_RECORD


# ── Delegation grants ─────────────────────────────────────────────────────────

class TestGrants:

    def test_valid_grant_allows_a_worker_to_read_a_managers_record(
        self, worker, grant_factory, now
    ):
        r = make_record(record_id="faiss:9#1", source=MANAGER_ID,
                        visibility=Visibility.GLOBAL)
        g = grant_factory(["faiss:9#1"])
        d = can_read(worker, r, [g], now)
        assert d.allowed
        assert d.reason == Reason.DELEGATION_GRANT
        assert d.matched_grant_id == g.grant_id

    def test_expired_grant_denies(self, worker, grant_factory, now):
        r = make_record(record_id="faiss:9#1", source=MANAGER_ID,
                        visibility=Visibility.GLOBAL)
        g = grant_factory(["faiss:9#1"], ttl_sec=60)
        d = can_read(worker, r, [g], now + timedelta(seconds=61))
        assert not d.allowed and d.reason == Reason.GRANT_EXPIRED

    def test_grant_expires_exactly_at_its_deadline(self, worker, grant_factory, now):
        r = make_record(record_id="faiss:9#1", source=MANAGER_ID,
                        visibility=Visibility.GLOBAL)
        g = grant_factory(["faiss:9#1"], ttl_sec=60)
        assert can_read(worker, r, [g], now + timedelta(seconds=59)).allowed
        assert not can_read(worker, r, [g], now + timedelta(seconds=60)).allowed

    def test_grant_does_not_cover_unnamed_records(self, worker, grant_factory, now):
        """Grants name explicit IDs — they never widen to a neighbourhood."""
        granted = make_record(record_id="faiss:9#1", source=MANAGER_ID,
                              visibility=Visibility.GLOBAL)
        other = make_record(record_id="faiss:9#2", source=MANAGER_ID,
                            visibility=Visibility.GLOBAL)
        g = grant_factory(["faiss:9#1"])
        assert can_read(worker, granted, [g], now).allowed
        d = can_read(worker, other, [g], now)
        assert not d.allowed and d.reason == Reason.LOCAL_ISOLATION

    def test_grant_issued_to_another_robot_is_ignored(self, worker, grant_factory, now):
        r = make_record(record_id="faiss:9#1", source=MANAGER_ID,
                        visibility=Visibility.GLOBAL)
        g = grant_factory(["faiss:9#1"], granted_to=OTHER_WORKER_ID)
        d = can_read(worker, r, [g], now)
        assert not d.allowed and d.reason == Reason.LOCAL_ISOLATION

    def test_absent_grant_denies(self, worker, now):
        r = make_record(record_id="faiss:9#1", source=MANAGER_ID,
                        visibility=Visibility.GLOBAL)
        d = can_read(worker, r, (), now)
        assert not d.allowed and d.reason == Reason.LOCAL_ISOLATION

    def test_grant_reaches_a_restricted_record(self, worker, grant_factory, now):
        r = make_record(record_id="faiss:9#1", source=MANAGER_ID,
                        visibility=Visibility.RESTRICTED)
        assert can_read(worker, r, [grant_factory(["faiss:9#1"])], now).allowed

    def test_grant_reaches_an_unattributed_legacy_record(
        self, worker, grant_factory, now
    ):
        r = make_record(record_id="faiss:9#1", source=None,
                        visibility=Visibility.LOCAL, scenario=None)
        assert can_read(worker, r, [grant_factory(["faiss:9#1"])], now).allowed


# ── Default deny ──────────────────────────────────────────────────────────────

class TestDefaultDeny:

    def test_missing_visibility_denies(self, manager, now):
        r = make_record(source=MANAGER_ID, visibility=None)
        d = can_read(manager, r, (), now)
        assert not d.allowed and d.reason == Reason.INVALID_VISIBILITY

    @pytest.mark.parametrize("bad", ["public", "GLOBAL_", "", 7, [], {"a": 1}])
    def test_unrecognised_visibility_denies(self, manager, now, bad):
        r = make_record(source=MANAGER_ID, visibility=bad)
        d = can_read(manager, r, (), now)
        assert not d.allowed and d.reason == Reason.INVALID_VISIBILITY

    def test_missing_access_level_denies(self, now):
        who = RobotIdentity(robot_id="x", scenario_id=SCENARIO, access_level=None)
        d = can_read(who, make_record(source="x"), (), now)
        assert not d.allowed and d.reason == Reason.UNKNOWN_ACCESS_LEVEL

    @pytest.mark.parametrize("bad", ["superuser", "admin", "GLOBAL_", "", 1])
    def test_unrecognised_access_level_denies(self, now, bad):
        who = RobotIdentity(robot_id="x", scenario_id=SCENARIO, access_level=bad)
        d = can_read(who, make_record(source="x"), (), now)
        assert not d.allowed and d.reason == Reason.UNKNOWN_ACCESS_LEVEL

    def test_unknown_access_level_beats_ownership(self, now):
        """An unparseable level denies even the robot's own record. Fail closed."""
        who = RobotIdentity(robot_id="x", scenario_id=SCENARIO, access_level="wizard")
        d = can_read(who, make_record(source="x"), (), now)
        assert not d.allowed and d.reason == Reason.UNKNOWN_ACCESS_LEVEL

    def test_unidentified_requester_denies(self, now):
        who = RobotIdentity(robot_id="", scenario_id=SCENARIO,
                            access_level=AccessLevel.GLOBAL)
        d = can_read(who, make_record(source=None, visibility=Visibility.GLOBAL), (), now)
        assert not d.allowed and d.reason == Reason.UNKNOWN_REQUESTER

    def test_missing_provenance_denies(self, manager, now):
        r = make_record(source=None, visibility=Visibility.GLOBAL)
        d = can_read(manager, r, (), now)
        assert not d.allowed and d.reason == Reason.MISSING_PROVENANCE

    def test_case_and_whitespace_are_tolerated_not_a_bypass(self, manager, now):
        """Parsing normalises, but only to the known set."""
        ok = make_record(source=WORKER_ID, visibility="  GLOBAL ")
        assert can_read(manager, ok, (), now).allowed
        bad = make_record(source=WORKER_ID, visibility=" glob al ")
        assert not can_read(manager, bad, (), now).allowed


# ── Decision shape ────────────────────────────────────────────────────────────

def test_decision_is_falsy_when_denied(worker, now):
    assert not can_read(worker, make_record(source=MANAGER_ID), (), now)


def test_decision_is_truthy_when_allowed(worker, now):
    assert can_read(worker, make_record(source=WORKER_ID), (), now)


def test_every_reason_constant_is_unique():
    """Reasons are a wire format — a collision would corrupt denial counts."""
    values = [v for k, v in vars(Reason).items() if not k.startswith("_")]
    assert len(values) == len(set(values))
